name = Passive
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = passive-layout

; Regions
regions[branding]          = Branding
regions[header]            = Header
regions[navigation]        = Navigation bar
regions[highlighted]       = Highlighted
regions[help]              = Help
regions[content]           = Content
regions[sidebar_first]     = First sidebar
regions[sidebar_second]    = Second sidebar
regions[postrow]           = Postrow
regions[postscript_first]  = Postscript first
regions[postscript_second] = Postscript second
regions[postscript_third]  = Postscript third
regions[copyright]         = Copyright
regions[footer]            = Footer

; Stylesheets
stylesheets[all][] = css/layouts/passive/passive.layout.css
